const $=x=>document.getElementById(x);let state=null,busy=false,shownAt=0,ownerMode=false,ownerStopped=false,remoteBusy=false,polling=false;
async function request(path,data){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),path==='/pilot/action'?300000:15000);try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:controller.signal});const j=await r.json();if(!r.ok)throw Error(j.error);return j}finally{clearTimeout(timer)}}
function controls(){document.querySelectorAll('button').forEach(b=>b.disabled=busy||remoteBusy);if(ownerMode){$('stop').disabled=false;$('shutdown').disabled=false;}if(ownerStopped){for(const id of ['send','stop','offer','microStart','microSubmit','microFeedback','microExit'])$(id).hidden=true;$('answer').disabled=true;$('choices').hidden=true;}}
function timer(){if(!state)return;const elapsed=Math.floor((Date.now()-shownAt)/1000);const taskLeft=Math.max(0,state.micro.seconds_left-elapsed),feedbackLeft=Math.max(0,(state.micro.feedback_seconds_left??300)-elapsed);$('budget').textContent=`已问 ${state.question_count}/6 · 探索剩余约 ${Math.max(0,state.seconds_left-elapsed)} 秒`+(state.micro.status==='RUNNING'?` · 任务剩余约 ${taskLeft} 秒`:'');if(state.blocked||state.processing||busy||ownerStopped)return;
 if(!state.closed&&state.seconds_left-elapsed<=0){$('send').hidden=true;$('choices').hidden=true;$('message').textContent='探索时间已到，请点击“停止探索”查看已保存的发现。';}
 if(['RUNNING','AWAITING_FEEDBACK'].includes(state.micro.status)){
  $('microSubmit').hidden=!state.micro.can_submit||taskLeft<=0;
  $('microFeedback').hidden=feedbackLeft<=0||(!state.micro.can_feedback&&!(state.micro.status==='RUNNING'&&taskLeft<=0));
  $('microExit').hidden=!state.micro.can_exit;
  if(feedbackLeft<=0){$('answer').hidden=true;$('message').textContent='微体验时间已到，可以退出任务并查看已保存的发现。';}
  else if(state.micro.status==='RUNNING'&&taskLeft<=0)$('message').textContent='任务时间已到，可以补充一次过程感受，也可以退出。';
 }}
function render(s){state=s;shownAt=Date.now();remoteBusy=!!s.processing;for(const id of ['result','micro','export'])$(id).hidden=false;$('preview').hidden=true;$('question').textContent=s.question||'';$('message').textContent=s.message||'';$('start').hidden=true;$('consent').parentElement.hidden=true;$('send').hidden=!s.question;$('stop').hidden=s.closed&&!remoteBusy;const liveQuestion=!!s.question;const choiceMode=liveQuestion&&s.response_mode==='SINGLE_CHOICE';$('choices').replaceChildren();$('choices').hidden=!choiceMode;$('answer').hidden=choiceMode||(!liveQuestion&&!['RUNNING','AWAITING_FEEDBACK'].includes(s.micro.status));$('answer').value='';if(choiceMode){$('choices').setAttribute('aria-label','选择一个最符合你的选项');for(const option of s.response_options||[]){const label=document.createElement('label');label.className='choice-option';const input=document.createElement('input');input.type='radio';input.name='response-choice';input.value=option.option_id;const text=document.createElement('span');text.textContent=option.label;label.append(input,text);$('choices').append(label)}}$('result').replaceChildren();if(s.display.mirror){let p=document.createElement('p');p.textContent=s.display.mirror.text;$('result').append(p)}for(const d of s.display.directions){let p=document.createElement('p');p.textContent='值得尝试的探索主题：'+d.theme;$('result').append(p)}$('offer').hidden=!!s.micro.instruction||!!s.question||s.blocked||remoteBusy;$('task').textContent=[s.micro.notice,s.micro.instruction].filter(Boolean).join('\n');$('microStart').hidden=s.micro.status!=='OFFERED';$('microSubmit').hidden=!s.micro.can_submit;$('microFeedback').hidden=!s.micro.can_feedback;$('microExit').hidden=!s.micro.can_exit;if(s.blocked||remoteBusy){$('choices').hidden=true;for(const id of ['offer','microStart','microSubmit','microFeedback','microExit','send'])$(id).hidden=true;}timer();controls();}
async function recover(){if(!ownerMode)return false;try{const p=await request('/owner/status',{});if(p.cancelled)ownerStopped=true;if(p.view)render(p.view);else remoteBusy=p.processing;controls();return !!p.view}catch(e){return false}}
async function guard(fn){if(busy||remoteBusy)return;busy=true;controls();$('message').textContent='正在处理，请不要重复提交…';try{await fn()}catch(e){const recovered=await recover();if(!recovered||(!state?.blocked&&!state?.processing))$('message').textContent=e.message==='PILOT_NOT_RELEASED'?'内测尚未开放，暂时不会调用AI或产生费用。':e.name==='AbortError'?'请求等待超时，未自动重试。请保留页面，系统会只读检查已保存的状态。':e.message;if(!recovered&&ownerMode){remoteBusy=true;$('message').textContent+=' 正在核对处理状态，不会重复发送回答。';}}finally{busy=false;controls();timer();if(ownerStopped)$('message').textContent='本次已停止，记录已保存。请点击“关闭本机服务”取得报告。';}}
async function act(action,extra={}){const s=await request('/pilot/action',{action,revision:state?.revision,request_id:crypto.randomUUID(),...extra});if(!ownerStopped)render(s)}
$('enter').onclick=()=>guard(async()=>{await request('/pilot/login',{code:$('code').value.trim()});$('code').value='';$('login').hidden=true;$('workspace').hidden=false;$('message').textContent='';try{render(await request('/pilot/action',{action:'view'}))}catch(e){if(e.message!=='START_REQUIRED')throw e}});
$('start').onclick=()=>{if(!$('consent').checked){$('message').textContent='请先确认参与说明。';return;}return guard(()=>act('start',{consent:true}));};
for(const [id,a]of Object.entries({microSubmit:'micro_submit',microFeedback:'micro_feedback'}))$(id).onclick=()=>{timer();if($(id).hidden||busy||remoteBusy)return;if(!$('answer').value.trim()||$('answer').value.length>12000){$('message').textContent='请写一句回答，也可以写“不知道”；最多12000字。';return;}return guard(async()=>{await act(a,{answer:$('answer').value});if(!state?.blocked)$('answer').value=''});};
$('send').onclick=()=>{timer();if($('send').hidden||busy||remoteBusy)return;if(state?.response_mode==='SINGLE_CHOICE'){const selected=document.querySelector('input[name="response-choice"]:checked');if(!selected){$('message').textContent='请选择一个选项，也可以选择“不确定”。';return;}const label=(state.response_options||[]).find(x=>x.option_id===selected.value)?.label;if(!label)return;$('answer').value='';return guard(()=>act('answer',{answer:label,selected_option_id:selected.value}));}if(!$('answer').value.trim()||$('answer').value.length>12000){$('message').textContent='请写一句回答，也可以写“不知道”；最多12000字。';return;}const answer=$('answer').value;return guard(async()=>{await act('answer',{answer,selected_option_id:null});if(!state?.blocked)$('answer').value=''});};
$('stop').onclick=async()=>{if(ownerMode&&(busy||remoteBusy)){await stopOwner();return;}await guard(()=>act('stop'));};$('offer').onclick=()=>guard(()=>act('micro_offer',{direction_id:state.display.directions[0]?.direction_id||null}));$('microStart').onclick=()=>guard(()=>act('micro_start',{opt_in:true}));$('microExit').onclick=()=>guard(()=>act(state.micro.status==='OFFERED'?'micro_decline':'micro_exit'));
$('export').onclick=()=>guard(async()=>{const data=await request('/pilot/action',{action:'export'});const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='我的探索记录.json';a.click();URL.revokeObjectURL(url);$('message').textContent='已导出。'});
setInterval(timer,1000);
$('preview').onclick=()=>guard(async()=>{const p=await request('/pilot/action',{action:'preview'});$('question').textContent=p.question;$('message').textContent=p.message;$('answer').hidden=false;$('answer').disabled=true;$('answer').placeholder='真实体验启用后，可在这里回答。预览不收集回答。';for(const id of ['send','stop','micro','export','start'])$(id).hidden=true;});
$('shutdown').onclick=async()=>{if(ownerMode&&(busy||remoteBusy)){await stopOwner();return;}await guard(async()=>{await request('/owner/shutdown',{});$('workspace').hidden=true;$('shutdown').hidden=true;$('message').textContent='本机服务已关闭。可以关闭此页面。';});};
function entryUI(entry){$('login').hidden=true;$('workspace').hidden=false;$('shutdown').hidden=false;for(const id of ['answer','choices','send','stop','result','micro','export'])$(id).hidden=true;if(entry.live_enabled){ownerMode=true;$('preview').hidden=true;$('message').textContent=`本人一次真实体验 · 本次新增最多${entry.incremental_limit_yuan??3}元，计入本人累计${entry.owner_total_limit_yuan??3}元及总计${entry.overall_limit_yuan??20}元内 · 失败即停，不重试。`;}else{$('start').hidden=true;$('consent').parentElement.hidden=true;$('notice').hidden=true;$('message').textContent='当前为Owner界面预览：尚未启用真实AI，无需输入密钥。';}}
(async()=>{const fragment=new URLSearchParams(location.hash.slice(1));const code=fragment.get('owner');if(code){history.replaceState(null,'',location.pathname);await guard(async()=>{await request('/pilot/login',{code});const entry=await request('/pilot/action',{action:'entry'});entryUI(entry);});return;}
 // The fragment is deliberately removed after login; resume via HttpOnly cookie.
 try{const p=await request('/owner/status',{});entryUI(p);ownerStopped=!!p.cancelled;if(p.view)render(p.view);controls();}catch(e){/* No owner ticket: retain ordinary invite login. */}
})();
async function stopOwner(){try{await request('/owner/stop',{});ownerStopped=true;$('send').hidden=true;$('stop').hidden=true;$('answer').disabled=true;$('choices').hidden=true;$('message').textContent='已收到停止请求，不会继续发起模型调用。已发出的请求可能仍计费，正在等待它结束并保存记录。';}catch(e){$('message').textContent='未能确认停止，请回到启动终端按 Control+C。';}}
setInterval(async()=>{if(!ownerMode||(!busy&&!remoteBusy)||polling)return;polling=true;try{const p=await request('/owner/status',{});if(!busy&&!remoteBusy)return;
 if(!busy&&p.view&&!p.processing&&!p.view.processing){render(p.view);if(ownerStopped)$('message').textContent='本次已停止，记录已保存。请点击“关闭本机服务”取得报告。';return;}
 if(!ownerStopped)$('message').textContent=`正在处理你的回答，已完成 ${p.completed_steps} 个处理步骤，当前步骤等待 ${p.waiting_seconds} 秒。你可以点击“停止探索”。`;
 }catch(e){}finally{polling=false}},2000);
